"""updated tables

Revision ID: 4dfd1b642737
Revises: fec078aef4a3
Create Date: 2023-10-25 10:14:05.076356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfd1b642737'
down_revision = 'fec078aef4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pets', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_owner', 'pets', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_owner', 'pets', type_='foreignkey')
    op.drop_column('pets', 'owner_id')
    op.drop_table('owners')
    # ### end Alembic commands ###
